### ISSUE TITLE
Missing colon in bondchars

### ISSUE THREAD

**Issue by mateuszrezler** [baoilleach/deepsmiles#10]
While working with SMILES having all their bonds explicit, I noticed the lack of a colon in `bondchars` variable. That's why something like this happens:

`>>> smiles_all_bonds_explicit = '[O]=[C](-[OH])-[c]1:[cH]:[c](-[OH]):[c](-[OH]):[c](-[OH]):[cH]:1'`
`>>> converter = deepsmiles.Converter(branches=True, rings=True)`
`>>> converter.encode(smiles_all_bonds_explicit)`
`'[O]=[C]-[OH])-[c]:[cH]:[c]-[OH]):[c]-[OH]):[c]-[OH]):[cH]:%12'` *12-membered ring*

After adding a colon to the line No. 11 in `encode.py`, the output is as expected:

`'[O]=[C]-[OH])-[c]:[cH]:[c]-[OH]):[c]-[OH]):[c]-[OH]):[cH]:6'` *6-membered ring*

Decoding still works correctly after this change.

**Comment by baoilleach** [comment]
Thanks for that. Looks like a safe change.

**Comment by mateuszrezler** [comment]
By the way, the dollar sign is not needed in this set, because it is not used to symbolize bonds in SMILES notation. But I am not completely sure about that.

**Comment by baoilleach** [comment]
Quadruple bond. Poorly documented though.
