### ISSUE TITLE
Did you try to implementate deepsmiles to chemical_vae coded by Rafa Gómez-Bombarelli etc.?

### ISSUE THREAD

**Issue by xuzhang5788** [baoilleach/deepsmiles#3]
Thank you for your great library.
It is such a great idea that we can insert this converter before encoding and after decoding.  Do you actually implement it into any vae model, such as chemical_vae built by Rafa Gómez-Bombarelli etc? Many thanks

**Comment by baoilleach** [comment]
No. I have never used any form of deep learning.
